version: "3.6"
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wordpress
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./PUBLIC:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 4
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${MYSQL_HOST}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./addon_files/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always
    ports:
      - 8000:3306

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    mem_limit: 1536m
    mem_reservation: 256M
    cpus: 2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_DIR:-./config/nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./addon_files/logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./PUBLIC}:/var/www/html
      - ${SSL_CERTS_DIR:-./addon_files/certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./addon_files/certs-data}:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    links:
      - mysql

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./addon_files/backup:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
      - MAX_BACKUPS=15
      # Make it small
      - GZIP_LEVEL=9