version: '2'

services:
    web_app:
        container_name: ao_web_app
        image: nginx:latest
        mem_limit: 512m
        mem_reservation: 128M
        cpus: 0.5
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./omega/public:/omega/public
            - ./omega/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - og-network
        depends_on: 
            - app
        links:
            - app
    app:
        container_name: ao_app
        image: php:fpm
        mem_limit: 512m
        mem_reservation: 128M
        cpus: 1
        volumes:
            - ./omega/public:/omega/public
        networks:
            - og-network
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DB=test_db
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=test_db
        volumes:
            - mysql_volume:/var/lib/mysql
        container_name: ao_mysql
        networks:
            - og-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        volumes:
            - /sessions
        container_name: ao_phpmyadmin
        networks:
            - og-network

networks:
    og-network:
        driver: bridge

volumes:
  mysql_volume: