version: "3.6"
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wordpress
    volumes:
      - ./_config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./PUBLIC:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 2
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mysql
    volumes:
      - ./_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_DIR:-./_config/nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./_.addon_files._/logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./PUBLIC}:/var/www/html
      - ${SSL_CERTS_DIR:-./_.addon_files._/certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./_.addon_files._/certs-data}:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8080:8080
